// Base de dados do catálogo de trocas.
// Uma entrada por troca; `incerto: true` marca nome cortado na interface do jogo (confirmar).
// `categoria`: Armas | Roupas | Acessórios | Proteção / Máscaras | Detectores e Dispositivos | Outros
const CATALOGO = [
  {
    item: "Fort-17",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Armas",
    materiais: [
      { nome: "Pacotes de café", qtd: 1 },
      { nome: "Porcas de parafuso", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171232.png",
  },
  {
    item: "APS Stechkin",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Armas",
    materiais: [
      { nome: "Cloro", qtd: 1 },
      { nome: "Água Sanitária", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171309.png",
  },
  {
    item: "Pistola FN57",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Armas",
    materiais: [
      { nome: "Spray Anti-Baratas", qtd: 1 },
      { nome: "Repelente", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171321.png",
  },
  {
    item: "Águia Negra",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Armas",
    materiais: [
      { nome: "Vaso Antigo", qtd: 1 },
      { nome: "Livro Antigo Danificado", qtd: 1 },
      { nome: "Carta Selada", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171333.png",
  },
  {
    item: "Taurus Raging Bull",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Armas",
    materiais: [
      { nome: "Frasco de Solução Salina", qtd: 1 },
      { nome: "Cartela de Remédios Preservada", qtd: 1, incerto: true },
      { nome: "Seringa Descartável", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171342.png",
  },
  {
    item: "Pistola Automática OTs-33",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Armas",
    materiais: [
      { nome: "Plugue em forma de T", qtd: 1, incerto: true },
      { nome: "VHS", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171400.png",
  },
  {
    item: "Fuzil de Assalto AKS-74U",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Armas",
    materiais: [
      { nome: "Termômetro Analógico", qtd: 1 },
      { nome: "Tubo de silicone", qtd: 1 },
      { nome: "Válvula de Pressão", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171443.png",
  },
  {
    item: "MP5A2",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Armas",
    materiais: [
      { nome: "Pedaço de acrílico", qtd: 1 },
      { nome: "GreenBat lithium battery", qtd: 1, incerto: true },
      { nome: "Girotacômetro militar", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171501.png",
  },
  {
    item: "Submetralhadora Saiga-9",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Armas",
    materiais: [
      { nome: "Combustível seco", qtd: 1 },
      { nome: "Analisador de Gás", qtd: 1 },
      { nome: "Pasta para soldagem a frio", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171511.png",
  },
  {
    item: "SPAS-12 Semi-Auto",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Armas",
    materiais: [
      { nome: "Ímã", qtd: 1 },
      { nome: "Controlador de motor", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171523.png",
  },
  {
    item: "SPAS-12 Pump",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Armas",
    materiais: [
      { nome: "Tubo corrugado militar", qtd: 1 },
      { nome: "Combustível", qtd: 1 },
      { nome: "Limpador de janelas", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171534.png",
  },
  {
    item: "Espingarda MP153",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Armas",
    materiais: [
      { nome: "Nuts", qtd: 1 },
      { nome: "Mars", qtd: 1 },
      { nome: "Snickers", qtd: 1 },
      { nome: "Bounty", qtd: 1 },
      { nome: "Amontoado de Açúcar Queimado", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171549.png",
  },
  {
    item: "Supressor GemTech Tundra",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Acessórios",
    materiais: [
      { nome: "Projeto", qtd: 1 },
      { nome: "Furadeira", qtd: 1 },
      { nome: "Pedaço de acrílico", qtd: 1 },
      { nome: "Pasta para soldagem a frio", qtd: 1, incerto: true },
      { nome: "Pendrive Militar", qtd: 1 },
      { nome: "Orelha de cão", qtd: 4 },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171559.png",
  },
  {
    item: "Máscara de Gás MSO",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Proteção / Máscaras",
    materiais: [
      { nome: "Pasta para soldagem a frio", qtd: 1, incerto: true },
      { nome: "Filtro de Água", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171608.png",
  },
  {
    item: "Mascara XM-40",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Proteção / Máscaras",
    materiais: [
      { nome: "Pasta para soldagem a frio", qtd: 1, incerto: true },
      { nome: "Peças de reposição SE", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171620.png",
  },
  {
    item: "Traje Sunrise",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Roupas",
    materiais: [
      { nome: "Tecido Ripstop", qtd: 1 },
      { nome: "Paracord", qtd: 1 },
      { nome: "Fita Métrica", qtd: 1 },
      { nome: "Pedaço de acrílico", qtd: 1 },
      { nome: "Fita Isolante", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171635.png",
  },
  {
    item: "Traje Sunrise",
    npc: "Barmen",
    lugar: "Rostok",
    categoria: "Roupas",
    materiais: [
      { nome: "Tecido Ripstop", qtd: 1 },
      { nome: "Paracord", qtd: 1 },
      { nome: "Fita Métrica", qtd: 1 },
      { nome: "Pedaço de acrílico", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barmen/Captura de tela 2026-07-19 171647.png",
  },
  {
    item: "Detector Otklik (Eco)",
    npc: "Sakharov",
    lugar: "Yantar",
    categoria: "Detectores e Dispositivos",
    materiais: [
      { nome: "Língua de Sanguessuga", qtd: 2 },
      { nome: "Feixe de fios", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Sakharov/Screenshot_12.png",
  },
  {
    item: "Detector Bear (Urso)",
    npc: "Sakharov",
    lugar: "Yantar",
    categoria: "Detectores e Dispositivos",
    materiais: [
      { nome: "Detector Otklik (Eco)", qtd: 1 },
      { nome: "Leitor de DVD", qtd: 1 },
      { nome: "Mão de Hazmatico", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Sakharov/Screenshot_1.png",
  },
  {
    item: "Detector Gilka (Galho)",
    npc: "Sakharov",
    lugar: "Yantar",
    categoria: "Detectores e Dispositivos",
    materiais: [
      { nome: "Projeto", qtd: 1 },
      { nome: "Crânio de Putrefato", qtd: 1 },
      { nome: "Garras de Escarro", qtd: 1 },
      { nome: "Ímã", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Sakharov/Screenshot_3.png",
  },
  {
    item: "Benelli M4",
    npc: "Sakharov",
    lugar: "Yantar",
    categoria: "Armas",
    materiais: [
      { nome: "Vaso Antigo", qtd: 1 },
      { nome: "Revista Playboy MAXIM", qtd: 1, incerto: true },
      { nome: "Spray Anti-Baratas", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Sakharov/Screenshot_5.png",
  },
  {
    item: "Kit Glock PDW",
    npc: "Sakharov",
    lugar: "Yantar",
    categoria: "Acessórios",
    materiais: [
      { nome: "Chave de Fenda", qtd: 1 },
      { nome: "Parafusos", qtd: 2 },
      { nome: "Peças de armas", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Sakharov/Screenshot_6.png",
  },
  {
    item: "Dosímetro V1",
    npc: "Sakharov",
    lugar: "Yantar",
    categoria: "Detectores e Dispositivos",
    materiais: [
      { nome: "Alicate Corta-Cabos", qtd: 1 },
      { nome: "Analisador de Gás", qtd: 1 },
      { nome: "Combustível seco", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Sakharov/Screenshot_7.png",
  },
  {
    item: "Mascara ZT42",
    npc: "Fox",
    lugar: "Cordon",
    categoria: "Proteção / Máscaras",
    materiais: [
      { nome: "Máscara de Gás GP-5", qtd: 1 },
      { nome: "Pata de Gato Bayun", qtd: 4 },
      { nome: "Casco de Javali", qtd: 4 },
    ],
    imagem: "Imagens/Trocas/Fox/Captura de tela 2026-07-19 220317.png",
  },
  {
    item: "Máscara de Gás CN-3a",
    npc: "Fox",
    lugar: "Cordon",
    categoria: "Proteção / Máscaras",
    materiais: [
      { nome: "Máscara de Gás GP-5", qtd: 1 },
      { nome: "Kit de Costura", qtd: 1 },
      { nome: "Mangueira corrugada", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Fox/Captura de tela 2026-07-19 220329.png",
  },
  {
    item: "Mossberg Maverick HS12",
    npc: "Fox",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Parafusos", qtd: 1 },
      { nome: "Chave de Fenda", qtd: 1 },
      { nome: "Capacitores", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Fox/Captura de tela 2026-07-19 220342.png",
  },
  {
    item: "Espingarda MP-18",
    npc: "Fox",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Pata de Flesh", qtd: 1 },
      { nome: "Pata de Gato Bayun", qtd: 3 },
    ],
    imagem: "Imagens/Trocas/Fox/Captura de tela 2026-07-19 220350.png",
  },
  {
    // Título cortado na borda da tela ("TOZ-10..."); TOZ-106 é a única espingarda de ferrolho conhecida
    item: "Espingarda de Ferrolho TOZ-106",
    npc: "Fox",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Pata de Flesh", qtd: 2 },
      { nome: "Pata de Gato Bayun", qtd: 2 },
      { nome: "Casco de Javali", qtd: 1 },
      { nome: "Mão de Zumbi", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Fox/Captura de tela 2026-07-19 220404.png",
  },
  {
    item: "MP 27M",
    npc: "Fox",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Rabo de Blind Dog", qtd: 3 },
      { nome: "Spray Anti-Baratas", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Fox/Captura de tela 2026-07-19 220410.png",
  },
  {
    item: "Carabina de repetição",
    npc: "Fox",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Pote de Pepino", qtd: 1 },
      { nome: "Cebola", qtd: 1 },
      { nome: "Repolho", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Fox/Captura de tela 2026-07-19 220416.png",
  },
  {
    item: "Submetralhadora Viper-5",
    npc: "Wolf",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Sucata de Metal", qtd: 1 },
      { nome: "WD40", qtd: 1 },
      { nome: "Peças de armas", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Wolf/Captura de tela 2026-07-19 230417.png",
  },
  {
    item: "Espingarda Higgins Model 583",
    npc: "Wolf",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Óleo em Spray para Armas", qtd: 1, incerto: true },
      { nome: "Graxa Industrial", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Wolf/Captura de tela 2026-07-19 230426.png",
  },
  {
    item: "UZI",
    npc: "Wolf",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Papel Higiênico", qtd: 1 },
      { nome: "Revista Playboy MAXIM", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Trocas/Wolf/Captura de tela 2026-07-19 230434.png",
  },
  {
    item: "Submetralhadora MP-40",
    npc: "Wolf",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Água Sanitária", qtd: 1 },
      { nome: "Limpador de Ralos de Cha", qtd: 1, incerto: true },
      { nome: "Alcalino para trocador", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Trocas/Wolf/Captura de tela 2026-07-19 230443.png",
  },
  {
    item: "CR-61 Skorpion",
    npc: "Wolf",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Capacitores", qtd: 1 },
      { nome: "Lâmpada", qtd: 1 },
      { nome: "Fita Isolante", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Wolf/Captura de tela 2026-07-19 230455.png",
  },
  {
    item: "Traje do Recruta",
    npc: "Wolf",
    lugar: "Cordon",
    categoria: "Roupas",
    materiais: [
      { nome: "Tecido de Fibra Poliamida", qtd: 1, incerto: true },
      { nome: "Ferramentas Médicas", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Wolf/Captura de tela 2026-07-19 230509.png",
  },
  {
    item: "Traje do Recruta",
    npc: "Wolf",
    lugar: "Cordon",
    categoria: "Roupas",
    materiais: [
      { nome: "Tecido Fleece", qtd: 1 },
      { nome: "Ferramentas Médicas", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Wolf/Captura de tela 2026-07-19 230517.png",
  },
  {
    item: "Traje do Recruta",
    npc: "Wolf",
    lugar: "Cordon",
    categoria: "Roupas",
    materiais: [
      { nome: "Tecido de Fibra de Aramida", qtd: 1, incerto: true },
      { nome: "Ferramentas Médicas", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Wolf/Captura de tela 2026-07-19 230527.png",
  },
  {
    item: "Deagle Estiloso",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Sabão", qtd: 1 },
      { nome: "Pasta de Dente", qtd: 1 },
      { nome: "Papel Higiênico", qtd: 1 },
      { nome: "Mão de Zumbi", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Captura de tela 2026-07-19 230909.png",
  },
  {
    item: "Revólver",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Grãos de café", qtd: 1 },
      { nome: "Pacote de Chá (Caixa)", qtd: 1 },
      { nome: "Casco de Javali", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Captura de tela 2026-07-19 230921.png",
  },
  {
    item: "Chaser-13",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Parafusos", qtd: 2 },
      { nome: "Martelo", qtd: 1 },
      { nome: "Sucata de Metal", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Captura de tela 2026-07-19 230938.png",
  },
  {
    item: "BK-12",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Casco de Javali", qtd: 3 },
      { nome: "Mão de Zumbi", qtd: 3 },
      { nome: "Cabeça de Tushkano", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Captura de tela 2026-07-19 230954.png",
  },
  {
    item: "Espingarda Izh-43",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Casco de Javali", qtd: 3 },
      { nome: "Pata de Gato Bayun", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Captura de tela 2026-07-19 231115.png",
  },
  {
    // Imagens/Sidorovich/Screenshot_6.png é duplicata desta troca (mesmo traje e requisitos) — não registrar
    item: "Traje de Novato",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Roupas",
    materiais: [
      { nome: "Rabo de Blind Dog", qtd: 4 },
      { nome: "Lâmpada", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Captura de tela 2026-07-19 231257.png",
  },
  {
    item: "Pistola Mauser C96 «Schnellfeuer»",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Armas",
    materiais: [
      { nome: "Seringa Descartável", qtd: 1 },
      { nome: "Ferramentas Médicas", qtd: 2 },
      { nome: "Frasco de Solução Salina", qtd: 2 },
      { nome: "Mão de Zumbi", qtd: 3 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Screenshot_1.png",
  },
  {
    item: "Máscara de Gás GP-5",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Proteção / Máscaras",
    materiais: [
      { nome: "Rabo de Blind Dog", qtd: 3 },
      { nome: "Mangueira corrugada", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Screenshot_2.png",
  },
  {
    item: "Detector Otklik (Eco)",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Detectores e Dispositivos",
    materiais: [
      { nome: "Detector 'Resposta' Quebrado", qtd: 1 },
      { nome: "Feixe de fios", qtd: 2 },
      { nome: "Capacitores", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Screenshot_3.png",
  },
  {
    item: "Detector Bear (Urso)",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Detectores e Dispositivos",
    materiais: [
      { nome: "Detector Otklik (Eco)", qtd: 1 },
      { nome: "\"ESPINHO\"", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Screenshot_4.png",
  },
  {
    item: "Traje de Novato",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Roupas",
    materiais: [
      { nome: "Cabeça de Tushkano", qtd: 4 },
      { nome: "Parafusos", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Screenshot_5.png",
  },
  {
    item: "Traje de Novato",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Roupas",
    materiais: [
      { nome: "Pata de Flesh", qtd: 4 },
      { nome: "Shampoo Schaman", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Screenshot_7.png",
  },
  {
    item: "Traje de Novato",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Roupas",
    materiais: [
      { nome: "Mão de Zumbi", qtd: 4 },
      { nome: "Parafusos", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Screenshot_8.png",
  },
  {
    item: "Traje de Novato",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Roupas",
    materiais: [
      { nome: "Casco de Javali", qtd: 4 },
      { nome: "Porcas de parafuso", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Screenshot_9.png",
  },
  {
    item: "Traje de Novato",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Roupas",
    materiais: [
      { nome: "Mão de Izlom", qtd: 4 },
      { nome: "Pasta de Dente", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Screenshot_10.png",
  },
  {
    item: "Traje de Novato",
    npc: "Sidorovich",
    lugar: "Cordon",
    categoria: "Roupas",
    materiais: [
      { nome: "Pata de Gato Bayun", qtd: 4 },
      { nome: "Fita Isolante", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Sidorovich/Screenshot_11.png",
  },
  {
    item: "Fuzil de Assalto AKS-74U",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Armas",
    materiais: [
      { nome: "Pasta de Dente", qtd: 1 },
      { nome: "Shampoo Schaman", qtd: 1 },
      { nome: "Sabão", qtd: 1 },
      { nome: "Repelente", qtd: 1 },
      { nome: "Lanterna", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_1.png",
  },
  {
    // Título pode ser "S590"/"590" — a fonte do jogo não distingue "5" de "S"
    item: "Espingarda Mossberg 5590",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Armas",
    materiais: [
      { nome: "Botijão de Propano", qtd: 1 },
      { nome: "Combustível seco", qtd: 1 },
      { nome: "Mangueira corrugada", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_2.png",
  },
  {
    item: "M12 Trench Gun",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Armas",
    materiais: [
      { nome: "Registro Médico", qtd: 1 },
      { nome: "Tanque de Combustível de Carro", qtd: 1, incerto: true },
      { nome: "Bateria de Carro", qtd: 1 },
      { nome: "Combustível", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_3.png",
  },
  {
    item: "AKS Danificada",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Armas",
    materiais: [
      { nome: "Sucata de Metal", qtd: 1 },
      { nome: "Furadeira manual", qtd: 1 },
      { nome: "Chave catraca", qtd: 1 },
      { nome: "Fita adesiva", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_4.png",
  },
  {
    item: "Espingarda Itacha 37",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Armas",
    materiais: [
      { nome: "Alicate Corta-Cabos", qtd: 1 },
      { nome: "Cortador de Unhas", qtd: 1 },
      { nome: "Tesoura para cortar metal", qtd: 1, incerto: true },
      { nome: "Chave catraca", qtd: 1 },
      { nome: "Fita Métrica", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_5.png",
  },
  {
    item: "Mosin serrado 91/30",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Armas",
    materiais: [
      { nome: "Leitor de DVD", qtd: 1 },
      { nome: "Televisor", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_6.png",
  },
  {
    item: "Submetralhadora PP-19-01 Vitya",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Armas",
    materiais: [
      { nome: "PP-91 Kedr", qtd: 1 },
      { nome: "Tecido de Fibra de Aramida", qtd: 1, incerto: true },
      { nome: "Mão de Izlom", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_7.png",
  },
  {
    item: "PP-2000",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Armas",
    materiais: [
      { nome: "Tecido de Fibra de Aramida", qtd: 1, incerto: true },
      { nome: "Tecido de Fibra Poliamida", qtd: 1, incerto: true },
      { nome: "Fita Métrica", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_8.png",
  },
  {
    item: "Faca Tática",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Armas",
    materiais: [
      { nome: "Cabeça de Tushkano", qtd: 3 },
      { nome: "Rabo de Blind Dog", qtd: 3 },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_9.png",
  },
  {
    item: "Faca para Coturnos",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Armas",
    materiais: [
      // Bug da interface: o tile mostra o ID interno "ratdog_Otrezano_La..." em vez do nome
      { nome: "ratdog_Otrezano_La", qtd: 2, incerto: true },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_10.png",
  },
  {
    item: "Faca DTs",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Armas",
    materiais: [
      { nome: "Mão de um Snork", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_11.png",
  },
  {
    item: "Faca de Caçador",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Armas",
    materiais: [
      { nome: "Tentáculos de Bloodsucker", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_12.png",
  },
  {
    item: "NVG Tier 1 - Monocular (PVS-14)",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Acessórios",
    materiais: [
      { nome: "Visão térmica militar", qtd: 1, incerto: true },
      { nome: "Projeto", qtd: 1 },
      { nome: "Olho de Poltergeist", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_13.png",
  },
  {
    item: "Traje Zorya",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Roupas",
    materiais: [
      { nome: "Tecido de Fibra de Aramida", qtd: 1, incerto: true },
      { nome: "Paracord", qtd: 1 },
      { nome: "Pedaço de acrílico", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_14.png",
  },
  {
    item: "Traje Zorya",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Roupas",
    materiais: [
      { nome: "Tecido Fleece", qtd: 1 },
      { nome: "Paracord", qtd: 1 },
      { nome: "Pedaço de acrílico", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_15.png",
  },
  {
    item: "Traje Zorya",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Roupas",
    materiais: [
      { nome: "Tecido Ripstop", qtd: 1 },
      { nome: "Paracord", qtd: 1 },
      { nome: "Pedaço de acrílico", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_16.png",
  },
  {
    item: "Granada de fumaça 40mm",
    npc: "Petrenko",
    lugar: "Bazar",
    categoria: "Outros",
    materiais: [
      { nome: "Pólvora Hawk", qtd: 3 },
      { nome: "Pacote de bicarbonato de sódio", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Trocas/Petrenko/Screenshot_17.png",
  },
  {
    item: "Fuzil de precisão M40",
    npc: "Coruja",
    lugar: "Yanov",
    categoria: "Armas",
    materiais: [
      { nome: "Fonte de Alimentação", qtd: 1 },
      { nome: "Peças de armas", qtd: 1 },
      { nome: "\"MEDUSA\"", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Coruja/Screenshot_1.png",
  },
  {
    item: "Fuzil de Assalto AK Tático",
    npc: "Coruja",
    lugar: "Yanov",
    categoria: "Armas",
    materiais: [
      { nome: "\"CLARÃO\"", qtd: 1 },
      { nome: "Tentáculos de Bloodsucker", qtd: 1 },
      { nome: "Cabeça de Psy Dog", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Coruja/Screenshot_2.png",
  },
  {
    item: "RPK-16",
    npc: "Coruja",
    lugar: "Yanov",
    categoria: "Armas",
    materiais: [
      { nome: "Cérebro de Psy Sucker", qtd: 1 },
      { nome: "Cabeça de Psy Dog", qtd: 3 },
      // A fonte do jogo não distingue bem "R"/"A"/"B" — pode ser "Unidade SAS"
      { nome: "Unidade SRS", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Trocas/Coruja/Screenshot_3.png",
  },
  {
    item: "Fuzil de Precisão VSK-94",
    npc: "Coruja",
    lugar: "Yanov",
    categoria: "Armas",
    materiais: [
      { nome: "Laptop reforçado", qtd: 1 },
      { nome: "Peças metálicas", qtd: 2 },
      { nome: "Cabeça de Tark", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Coruja/Screenshot_19.png",
  },
  {
    item: "Fuzil SKS Tático",
    npc: "Barbudo",
    lugar: "Skadovsk (Zaton)",
    categoria: "Armas",
    materiais: [
      // A fonte do jogo não distingue "S" de "5"; o ícone é um SKS — pode ser "SKS 59/66"
      { nome: "SK 59/66", qtd: 1, incerto: true },
      { nome: "Anel", qtd: 1 },
      { nome: "Revista Playboy MAXIM", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Trocas/Barbudo/Screenshot_2.png",
  },
  {
    item: "SVDm-2",
    npc: "Barbudo",
    lugar: "Skadovsk (Zaton)",
    categoria: "Armas",
    materiais: [
      { nome: "Anel de Ouro", qtd: 1 },
      // A fonte do jogo não distingue bem "R"/"A"/"B" — pode ser "Unidade SAS"
      { nome: "Unidade SRS", qtd: 1, incerto: true },
      { nome: "Olho de Poltergeist", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barbudo/Screenshot_3.png",
  },
  {
    item: "M16A1",
    npc: "Barbudo",
    lugar: "Skadovsk (Zaton)",
    categoria: "Armas",
    materiais: [
      { nome: "Dente de ouro", qtd: 1 },
      { nome: "Memória RAM", qtd: 2 },
      { nome: "Cérebro de Controlador", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barbudo/Screenshot_4.png",
  },
  {
    // Título cortado nas duas bordas da tela ("uzil de Assalto AK-74 Modificad")
    item: "Fuzil de Assalto AK-74 Modificado",
    npc: "Barbudo",
    lugar: "Skadovsk (Zaton)",
    categoria: "Armas",
    materiais: [
      { nome: "Tentáculos de Bloodsucker", qtd: 1 },
      { nome: "\"SERRA\"", qtd: 1 },
      { nome: "Módulo de Navegação Integrado", qtd: 1, incerto: true },
      { nome: "Mão de Kartik", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barbudo/Screenshot_5.png",
  },
  {
    item: "KS-23",
    npc: "Barbudo",
    lugar: "Skadovsk (Zaton)",
    categoria: "Armas",
    materiais: [
      { nome: "\"KAFIO\"", qtd: 1, incerto: true },
      { nome: "Bateria militar 6-STEN-1", qtd: 1, incerto: true },
      { nome: "Coração de Quimera", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barbudo/Screenshot_6.png",
  },
  {
    item: "Detector Gilka (Galho)",
    npc: "Barbudo",
    lugar: "Skadovsk (Zaton)",
    categoria: "Detectores e Dispositivos",
    materiais: [
      { nome: "Detector Bear (Urso)", qtd: 1 },
      { nome: "\"BATERIA\"", qtd: 1 },
      { nome: "Ímã", qtd: 1 },
      { nome: "Capacitores", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barbudo/Screenshot_7.png",
  },
  {
    item: "Gravador Milga Fm-301",
    npc: "Barbudo",
    lugar: "Skadovsk (Zaton)",
    categoria: "Detectores e Dispositivos",
    materiais: [
      { nome: "Caixa de charutos", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barbudo/Screenshot_8.png",
  },
  {
    item: "Mira Kobra",
    npc: "Barbudo",
    lugar: "Skadovsk (Zaton)",
    categoria: "Acessórios",
    materiais: [
      { nome: "Chave de fenda", qtd: 1 },
      { nome: "Unidade flash segura", qtd: 1 },
      { nome: "Parafusos", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barbudo/Screenshot_9.png",
  },
  {
    item: "Mira Baraka",
    npc: "Barbudo",
    lugar: "Skadovsk (Zaton)",
    categoria: "Acessórios",
    materiais: [
      { nome: "Chave de Fenda", qtd: 1 },
      { nome: "Pendrive Militar", qtd: 1 },
      { nome: "Porcas de parafuso", qtd: 1 },
    ],
    imagem: "Imagens/Trocas/Barbudo/Screenshot_10.png",
  },
  {
    item: "Capacete de enduro",
    npc: "Barbudo",
    lugar: "Skadovsk (Zaton)",
    categoria: "Proteção / Máscaras",
    materiais: [
      { nome: "Cobertura de capacete de enduro", qtd: 1, incerto: true },
      { nome: "Protetor bucal de capacete de enduro", qtd: 1, incerto: true },
      { nome: "Mão de Izlom", qtd: 2 },
    ],
    imagem: "Imagens/Trocas/Barbudo/Screenshot_11.png",
  },
];
