// Base de dados do catálogo de trocas.
// Uma entrada por troca; `incerto: true` marca nome cortado na interface do jogo (confirmar).
const CATALOGO = [
  {
    item: "Fort-17",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Pacotes de café", qtd: 1 },
      { nome: "Porcas de parafuso", qtd: 1 },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171232.png",
  },
  {
    item: "APS Stechkin",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Cloro", qtd: 1 },
      { nome: "Água Sanitária", qtd: 1 },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171309.png",
  },
  {
    item: "Pistola FN57",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Spray Anti-Baratas", qtd: 1 },
      { nome: "Repelente", qtd: 1 },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171321.png",
  },
  {
    item: "Águia Negra",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Vaso Antigo", qtd: 1 },
      { nome: "Livro Antigo Danificado", qtd: 1 },
      { nome: "Carta Selada", qtd: 1 },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171333.png",
  },
  {
    item: "Taurus Raging Bull",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Frasco de Solução Salina", qtd: 1 },
      { nome: "Cartela de Remédios Preservada", qtd: 1, incerto: true },
      { nome: "Seringa Descartável", qtd: 1 },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171342.png",
  },
  {
    item: "Pistola Automática OTs-33",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Plugue em forma de T", qtd: 1, incerto: true },
      { nome: "VHS", qtd: 1 },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171400.png",
  },
  {
    item: "Fuzil de Assalto AKS-74U",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Termômetro Analógico", qtd: 1 },
      { nome: "Tubo de silicone", qtd: 1 },
      { nome: "Válvula de Pressão", qtd: 1 },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171443.png",
  },
  {
    item: "MP5A2",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Pedaço de acrílico", qtd: 1 },
      { nome: "GreenBat lithium battery", qtd: 1, incerto: true },
      { nome: "Girotacômetro militar", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171501.png",
  },
  {
    item: "Submetralhadora Saiga-9",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Combustível seco", qtd: 1 },
      { nome: "Analisador de Gás", qtd: 1 },
      { nome: "Pasta para soldagem a frio", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171511.png",
  },
  {
    item: "SPAS-12 Semi-Auto",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Ímã", qtd: 1 },
      { nome: "Controlador de motor", qtd: 1 },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171523.png",
  },
  {
    item: "SPAS-12 Pump",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Tubo corrugado militar", qtd: 1 },
      { nome: "Combustível", qtd: 1 },
      { nome: "Limpador de janelas", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171534.png",
  },
  {
    item: "Espingarda MP153",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Nuts", qtd: 1 },
      { nome: "Mars", qtd: 1 },
      { nome: "Snickers", qtd: 1 },
      { nome: "Bounty", qtd: 1 },
      { nome: "Amontoado de Açúcar Queimado", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171549.png",
  },
  {
    item: "Supressor GemTech Tundra",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Projeto", qtd: 1 },
      { nome: "Furadeira", qtd: 1 },
      { nome: "Pedaço de acrílico", qtd: 1 },
      { nome: "Pasta para soldagem a frio", qtd: 1, incerto: true },
      { nome: "Pendrive Militar", qtd: 1 },
      { nome: "Orelha de cão", qtd: 4 },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171559.png",
  },
  {
    item: "Máscara de Gás MSO",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Pasta para soldagem a frio", qtd: 1, incerto: true },
      { nome: "Filtro de Água", qtd: 1 },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171608.png",
  },
  {
    item: "Mascara XM-40",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Pasta para soldagem a frio", qtd: 1, incerto: true },
      { nome: "Peças de reposição SE", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171620.png",
  },
  {
    item: "Traje Sunrise",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Tecido Ripstop", qtd: 1 },
      { nome: "Paracord", qtd: 1 },
      { nome: "Fita Métrica", qtd: 1 },
      { nome: "Pedaço de acrílico", qtd: 1 },
      { nome: "Fita Isolante", qtd: 1 },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171635.png",
  },
  {
    item: "Traje Sunrise",
    npc: "Barmen",
    lugar: "Rostok",
    materiais: [
      { nome: "Tecido Ripstop", qtd: 1 },
      { nome: "Paracord", qtd: 1 },
      { nome: "Fita Métrica", qtd: 1 },
      { nome: "Pedaço de acrílico", qtd: 1 },
    ],
    imagem: "Imagens/Barmen/Captura de tela 2026-07-19 171647.png",
  },
  {
    item: "Detector Otklik (Eco)",
    npc: "Sakharov",
    lugar: "Yantar",
    materiais: [
      { nome: "Língua de Sanguessuga", qtd: 2 },
      { nome: "Material desconhecido", qtd: 2, incerto: true },
    ],
    imagem: "Imagens/Sakharov/Captura de tela 2026-07-19 184621.png",
  },
  {
    item: "Detector Bear (Urso)",
    npc: "Sakharov",
    lugar: "Yantar",
    materiais: [
      { nome: "Detector Otklik (Eco)", qtd: 1 },
      { nome: "Leitor de DVD", qtd: 1 },
      { nome: "Mão de Hazmatico", qtd: 1 },
    ],
    imagem: "Imagens/Sakharov/Captura de tela 2026-07-19 184703.png",
  },
  {
    item: "Detector Gilka (Galho)",
    npc: "Sakharov",
    lugar: "Yantar",
    materiais: [
      { nome: "Projeto", qtd: 1 },
      { nome: "Crânio de Putrefato", qtd: 1 },
      { nome: "Garras de Escarro", qtd: 1 },
      { nome: "Ímã", qtd: 1 },
    ],
    imagem: "Imagens/Sakharov/Captura de tela 2026-07-19 185300.png",
  },
  {
    item: "Benelli M4",
    npc: "Sakharov",
    lugar: "Yantar",
    materiais: [
      { nome: "Vaso Antigo", qtd: 1 },
      { nome: "Revista Playboy MAXIM", qtd: 1, incerto: true },
      { nome: "Spray Anti-Baratas", qtd: 1 },
    ],
    imagem: "Imagens/Sakharov/Captura de tela 2026-07-19 185308.png",
  },
  {
    item: "Kit Glock PDW",
    npc: "Sakharov",
    lugar: "Yantar",
    materiais: [
      { nome: "Chave de Fenda", qtd: 1 },
      { nome: "Material desconhecido", qtd: 2, incerto: true },
      { nome: "Peças de armas", qtd: 1 },
    ],
    imagem: "Imagens/Sakharov/Captura de tela 2026-07-19 185317.png",
  },
  {
    item: "Dosímetro V1",
    npc: "Sakharov",
    lugar: "Yantar",
    materiais: [
      { nome: "Alicate Corta-Cabos", qtd: 1 },
      { nome: "Material desconhecido", qtd: 1, incerto: true },
      { nome: "Combustível seco", qtd: 2 },
    ],
    imagem: "Imagens/Sakharov/Captura de tela 2026-07-19 185324.png",
  },
  {
    item: "Mascara ZT42",
    npc: "Fox",
    lugar: "Cordon",
    materiais: [
      { nome: "Máscara de Gás GP-5", qtd: 1 },
      { nome: "Pata de Gato Bayun", qtd: 4 },
      { nome: "Casco de Javali", qtd: 4 },
    ],
    imagem: "Imagens/Fox/Captura de tela 2026-07-19 220317.png",
  },
  {
    item: "Máscara de Gás CN-3a",
    npc: "Fox",
    lugar: "Cordon",
    materiais: [
      { nome: "Máscara de Gás GP-5", qtd: 1 },
      { nome: "Kit de Costura", qtd: 1 },
      { nome: "Mangueira corrugada", qtd: 1 },
    ],
    imagem: "Imagens/Fox/Captura de tela 2026-07-19 220329.png",
  },
  {
    item: "Mossberg Maverick HS12",
    npc: "Fox",
    lugar: "Cordon",
    materiais: [
      { nome: "Parafusos", qtd: 1 },
      { nome: "Chave de Fenda", qtd: 1 },
      { nome: "Capacitores", qtd: 1 },
    ],
    imagem: "Imagens/Fox/Captura de tela 2026-07-19 220342.png",
  },
  {
    item: "Espingarda MP-18",
    npc: "Fox",
    lugar: "Cordon",
    materiais: [
      { nome: "Pata de Flesh", qtd: 1 },
      { nome: "Pata de Gato Bayun", qtd: 3 },
    ],
    imagem: "Imagens/Fox/Captura de tela 2026-07-19 220350.png",
  },
  {
    // Título cortado na borda da tela ("TOZ-10..."); TOZ-106 é a única espingarda de ferrolho conhecida
    item: "Espingarda de Ferrolho TOZ-106",
    npc: "Fox",
    lugar: "Cordon",
    materiais: [
      { nome: "Pata de Flesh", qtd: 2 },
      { nome: "Pata de Gato Bayun", qtd: 2 },
      { nome: "Casco de Javali", qtd: 1 },
      { nome: "Mão de Zumbi", qtd: 2 },
    ],
    imagem: "Imagens/Fox/Captura de tela 2026-07-19 220404.png",
  },
  {
    item: "MP 27M",
    npc: "Fox",
    lugar: "Cordon",
    materiais: [
      { nome: "Rabo de Blind Dog", qtd: 3 },
      { nome: "Spray Anti-Baratas", qtd: 1 },
    ],
    imagem: "Imagens/Fox/Captura de tela 2026-07-19 220410.png",
  },
  {
    item: "Carabina de repetição",
    npc: "Fox",
    lugar: "Cordon",
    materiais: [
      { nome: "Pote de Pepino", qtd: 1 },
      { nome: "Cebola", qtd: 1 },
      { nome: "Repolho", qtd: 1 },
    ],
    imagem: "Imagens/Fox/Captura de tela 2026-07-19 220416.png",
  },
  {
    item: "Submetralhadora Viper-5",
    npc: "Wolf",
    lugar: "Cordon",
    materiais: [
      { nome: "Sucata de Metal", qtd: 1 },
      { nome: "WD40", qtd: 1 },
      { nome: "Peças de armas", qtd: 1 },
    ],
    imagem: "Imagens/Wolf/Captura de tela 2026-07-19 230417.png",
  },
  {
    item: "Espingarda Higgins Model 583",
    npc: "Wolf",
    lugar: "Cordon",
    materiais: [
      { nome: "Óleo em Spray para Armas", qtd: 1, incerto: true },
      { nome: "Graxa Industrial", qtd: 1 },
    ],
    imagem: "Imagens/Wolf/Captura de tela 2026-07-19 230426.png",
  },
  {
    item: "UZI",
    npc: "Wolf",
    lugar: "Cordon",
    materiais: [
      { nome: "Papel Higiênico", qtd: 1 },
      { nome: "Revista Playboy MAXIM", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Wolf/Captura de tela 2026-07-19 230434.png",
  },
  {
    item: "Submetralhadora MP-40",
    npc: "Wolf",
    lugar: "Cordon",
    materiais: [
      { nome: "Água Sanitária", qtd: 1 },
      { nome: "Limpador de Ralos de Cha", qtd: 1, incerto: true },
      { nome: "Alcalino para trocador", qtd: 1, incerto: true },
    ],
    imagem: "Imagens/Wolf/Captura de tela 2026-07-19 230443.png",
  },
  {
    item: "CR-61 Skorpion",
    npc: "Wolf",
    lugar: "Cordon",
    materiais: [
      { nome: "Capacitores", qtd: 1 },
      { nome: "Lâmpada", qtd: 1 },
      { nome: "Fita Isolante", qtd: 1 },
    ],
    imagem: "Imagens/Wolf/Captura de tela 2026-07-19 230455.png",
  },
  {
    item: "Traje do Recruta",
    npc: "Wolf",
    lugar: "Cordon",
    materiais: [
      { nome: "Tecido de Fibra Poliamida", qtd: 1, incerto: true },
      { nome: "Ferramentas Médicas", qtd: 1 },
    ],
    imagem: "Imagens/Wolf/Captura de tela 2026-07-19 230509.png",
  },
  {
    item: "Traje do Recruta",
    npc: "Wolf",
    lugar: "Cordon",
    materiais: [
      { nome: "Tecido Fleece", qtd: 1 },
      { nome: "Ferramentas Médicas", qtd: 1 },
    ],
    imagem: "Imagens/Wolf/Captura de tela 2026-07-19 230517.png",
  },
  {
    item: "Traje do Recruta",
    npc: "Wolf",
    lugar: "Cordon",
    materiais: [
      { nome: "Tecido de Fibra de Aramida", qtd: 1, incerto: true },
      { nome: "Ferramentas Médicas", qtd: 1 },
    ],
    imagem: "Imagens/Wolf/Captura de tela 2026-07-19 230527.png",
  },
  {
    item: "Deagle Estiloso",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Sabão", qtd: 1 },
      { nome: "Pasta de Dente", qtd: 1 },
      { nome: "Papel Higiênico", qtd: 1 },
      { nome: "Mão de Zumbi", qtd: 2 },
    ],
    imagem: "Imagens/Sidorovich/Captura de tela 2026-07-19 230909.png",
  },
  {
    item: "Revólver",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Grãos de café", qtd: 1 },
      { nome: "Pacote de Chá (Caixa)", qtd: 1 },
      { nome: "Casco de Javali", qtd: 2 },
    ],
    imagem: "Imagens/Sidorovich/Captura de tela 2026-07-19 230921.png",
  },
  {
    item: "Chaser-13",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Parafusos", qtd: 2 },
      { nome: "Martelo", qtd: 1 },
      { nome: "Sucata de Metal", qtd: 1 },
    ],
    imagem: "Imagens/Sidorovich/Captura de tela 2026-07-19 230938.png",
  },
  {
    item: "BK-12",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Casco de Javali", qtd: 3 },
      { nome: "Mão de Zumbi", qtd: 3 },
      { nome: "Cabeça de Tushkano", qtd: 2 },
    ],
    imagem: "Imagens/Sidorovich/Captura de tela 2026-07-19 230954.png",
  },
  {
    item: "Espingarda Izh-43",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Casco de Javali", qtd: 3 },
      { nome: "Pata de Gato Bayun", qtd: 2 },
    ],
    imagem: "Imagens/Sidorovich/Captura de tela 2026-07-19 231115.png",
  },
  {
    // Imagens/Sidorovich/Screenshot_6.png é duplicata desta troca (mesmo traje e requisitos) — não registrar
    item: "Traje de Novato",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Rabo de Blind Dog", qtd: 4 },
      { nome: "Lâmpada", qtd: 2 },
    ],
    imagem: "Imagens/Sidorovich/Captura de tela 2026-07-19 231257.png",
  },
  {
    item: "Pistola Mauser C96 «Schnellfeuer»",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Seringa Descartável", qtd: 1 },
      { nome: "Ferramentas Médicas", qtd: 2 },
      { nome: "Frasco de Solução Salina", qtd: 2 },
      { nome: "Mão de Zumbi", qtd: 3 },
    ],
    imagem: "Imagens/Sidorovich/Screenshot_1.png",
  },
  {
    item: "Máscara de Gás GP-5",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Rabo de Blind Dog", qtd: 3 },
      { nome: "Mangueira corrugada", qtd: 1 },
    ],
    imagem: "Imagens/Sidorovich/Screenshot_2.png",
  },
  {
    item: "Detector Otklik (Eco)",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Detector 'Resposta' Quebrado", qtd: 1 },
      { nome: "Feixe de fios", qtd: 2 },
      { nome: "Capacitores", qtd: 2 },
    ],
    imagem: "Imagens/Sidorovich/Screenshot_3.png",
  },
  {
    item: "Detector Bear (Urso)",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Detector Otklik (Eco)", qtd: 1 },
      { nome: "\"ESPINHO\"", qtd: 1 },
    ],
    imagem: "Imagens/Sidorovich/Screenshot_4.png",
  },
  {
    item: "Traje de Novato",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Cabeça de Tushkano", qtd: 4 },
      { nome: "Parafusos", qtd: 2 },
    ],
    imagem: "Imagens/Sidorovich/Screenshot_5.png",
  },
  {
    item: "Traje de Novato",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Pata de Flesh", qtd: 4 },
      { nome: "Shampoo Schaman", qtd: 2 },
    ],
    imagem: "Imagens/Sidorovich/Screenshot_7.png",
  },
  {
    item: "Traje de Novato",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Mão de Zumbi", qtd: 4 },
      { nome: "Parafusos", qtd: 2 },
    ],
    imagem: "Imagens/Sidorovich/Screenshot_8.png",
  },
  {
    item: "Traje de Novato",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Casco de Javali", qtd: 4 },
      { nome: "Porcas de parafuso", qtd: 2 },
    ],
    imagem: "Imagens/Sidorovich/Screenshot_9.png",
  },
  {
    item: "Traje de Novato",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Mão de Izlom", qtd: 4 },
      { nome: "Pasta de Dente", qtd: 2 },
    ],
    imagem: "Imagens/Sidorovich/Screenshot_10.png",
  },
  {
    item: "Traje de Novato",
    npc: "Sidorovich",
    lugar: "Cordon",
    materiais: [
      { nome: "Pata de Gato Bayun", qtd: 4 },
      { nome: "Fita Isolante", qtd: 2 },
    ],
    imagem: "Imagens/Sidorovich/Screenshot_11.png",
  },
];
